# Generated by Django 4.1.2 on 2022-10-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('displayname', models.CharField(blank=True, max_length=100)),
                ('password_hash', models.CharField(max_length=500)),
                ('img', models.ImageField(blank=True, upload_to='user/%Y/%m/%d')),
                ('main_address', models.CharField(blank=True, max_length=500)),
                ('favorities', models.JSONField()),
                ('balance', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('login',),
            },
        ),
    ]
