# Generated by Django 4.1.2 on 2022-10-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_displayname_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favorities',
            new_name='favourites',
        ),
    ]
